anki:
  decks:
    - manga
    - novel
    - HT
    - manga_test
  models: 
    - manga
    - novel
  anki_api_url: http://127.0.0.1:8765
  vits_api_url: http://127.0.0.1:23456

vits:
  language: ja
  gui_voice: 342
  gui_length: 1
  voice_exp: 328
  voice_sen: 342
  length: 1.1

mecab:
  cixingcolor:
    形容詞: "rgba(255,225,243,0.4)"
    形状詞: "rgba(242,201,226,0.4)"
    副詞: "rgba(208,150,234,0.4)"
    名詞: "rgba(254,244,123,0.4)"
    代名詞: "rgba(240,255,255)"
    動詞: "rgba(185,233,134,0.4)"
    助詞: "rgba(148,215,221,0.4)"
    助動詞: "rgba(70,70,70,0.4)"
    感動詞: "rgba(255,235,205,0.4)"
    接頭辞: "rgba(0,0,255,0.4)"
    接尾辞: "rgba(138,43,226,0.4)"
    接続詞: "rgba(165,42,42,0.4)"
    指示詞: "rgba(222,184,135,0.4)"
    連体詞: "rgba(95,158,160,0.4)"
    判定詞: "rgba(127,255,0,0.4)"
    補助記号: "rgba(210,105,30,0.4)"
    記号: "rgba(255,127,80,0.4)"
    空白: "rgba(255,255,255,0.4)"
